# Generated by Django 6.0.4 on 2026-04-19 12:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='auto_issued_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial_issued', 'Partially Issued'), ('waiting_po', 'Waiting For PO'), ('ready_from_grn', 'Ready From GRN'), ('issued', 'Issued')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='short_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='issuance',
            name='system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shortage_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.inventoryrequest'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='inventory_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='inventory.inventoryrequest'),
        ),
    ]
